server:
  port: 8090

spring:
  r2dbc:
    url: r2dbc:postgresql://db:5432/testdb
    #url: r2dbc:postgresql://localhost:5432/testdb
    username: admin
    password: admin
    initialization-mode: always

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
